SHOW TABLES;

SELECT * FROM Online_Retail_clean;


-------------- Monthly Sales Trend -----------

CREATE VIEW MonthlySales AS
SELECT DATE_FORMAT(STR_TO_DATE(InvoiceDate, '%m/%d/%y %H:%i'), '%Y-%m') AS Month,
       SUM(Quantity * UnitPrice) AS TotalRevenue
FROM Online_Retail_clean
GROUP BY Month;


SELECT * FROM monthlysales;



------- Top Selling Products ----------

# Identify and visualize the top selling products based on total quantity.

CREATE VIEW TopSellingProducts AS
SELECT StockCode, Description, SUM(Quantity) AS TotalQuantity
FROM Online_Retail_clean
GROUP BY StockCode, Description
ORDER BY TotalQuantity DESC
LIMIT 10;


SELECT * FROM topsellingproducts;



--- Customer Segmentation --------

# Segment customers based on their spending behavior.

CREATE VIEW CustomerSegments AS
SELECT CustomerID,
       CASE
           WHEN SUM(Quantity * UnitPrice) > 1000 THEN 'High Spender'
           WHEN SUM(Quantity * UnitPrice) > 500 THEN 'Medium Spender'
           ELSE 'Low Spender'
       END AS CustomerSegment
FROM Online_Retail_clean
GROUP BY CustomerID;

SELECT * FROM CustomerSegments;


------ Revenue by Country   --------------------------
# Visualize revenue generated by different countries

CREATE VIEW RevenueByCountry AS
SELECT Country, SUM(Quantity * UnitPrice) AS TotalRevenue
FROM Online_Retail_clean
GROUP BY Country
ORDER BY TotalRevenue DESC; 

SELECT * FROM RevenueByCountry;





----- Monthly Repeat Purchase Rate  ----------------

# Analyze the percentage of customers who made repeat purchases each month.

CREATE VIEW MonthlyRepeatPurchase AS
SELECT 
    Month,
    COUNT(DISTINCT CASE WHEN RepeatPurchaseCount > 1 THEN CustomerID END) AS RepeatCustomers,
    COUNT(DISTINCT CustomerID) AS TotalCustomers
FROM (
    SELECT 
        DATE_FORMAT(STR_TO_DATE(InvoiceDate, '%m/%d/%y %H:%i'), '%Y-%m') AS Month,
        CustomerID,
        COUNT(DISTINCT InvoiceNo) AS RepeatPurchaseCount
    FROM Online_Retail_clean
    GROUP BY Month, CustomerID
) AS CustomerRepeatPurchases
GROUP BY Month;



SELECT * FROM monthlyrepeatpurchase;